const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.Function,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Plugins.Button,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.ScriptsInEvents.GameEvents_Event2_Act1,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetPos,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAchievementsClose,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsClose,
		C3.Plugins.Button.Acts.SetPos,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.ScriptsInEvents.MenuEvents_Event11_Act1,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsShare,
		C3.Behaviors.Bullet.Cnds.IsEnabled
	];
};
self.C3_JsPropNameTable = [
	{IsMatched: 0},
	{IsMoving: 0},
	{Trigger: 0},
	{Color: 0},
	{Col: 0},
	{DY: 0},
	{BlockY: 0},
	{Row: 0},
	{Peram: 0},
	{Block: 0},
	{Col1: 0},
	{Arr_X: 0},
	{Arr_Y: 0},
	{Col2: 0},
	{Touch: 0},
	{SwapArray: 0},
	{MainArray: 0},
	{Function: 0},
	{Browser: 0},
	{Audio: 0},
	{Keyboard: 0},
	{Particles: 0},
	{LocalStorage: 0},
	{Sprite: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Particles4: 0},
	{Particles5: 0},
	{Particles6: 0},
	{Sprite8: 0},
	{bg_sprite: 0},
	{menuplaybtn: 0},
	{Синусоид: 0},
	{Sprite9: 0},
	{Sprite11: 0},
	{Textscores: 0},
	{Textyours: 0},
	{yourscoretxt: 0},
	{yourhiscoretxt: 0},
	{Textyourshiscore2: 0},
	{btn_quit: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Text: 0},
	{Text2: 0},
	{Sprite12: 0},
	{Text3: 0},
	{btn_restart: 0},
	{barra_score: 0},
	{distancesguisheet: 0},
	{home: 0},
	{image3: 0},
	{image4: 0},
	{image5: 0},
	{Магия3ВРяд: 0},
	{hiclipartcom: 0},
	{share: 0},
	{Поворот: 0},
	{Пуля: 0},
	{Block3: 0},
	{Block4: 0},
	{Замкнутость: 0},
	{PADAET: 0},
	{PADAET2: 0},
	{PADAET3: 0},
	{SADF: 0},
	{БезИменил: 0},
	{barra_score1: 0},
	{image: 0},
	{image6: 0},
	{старт: 0},
	{бан: 0},
	{вид: 0},
	{GamePush: 0},
	{Pause: 0},
	{record: 0},
	{GameOn: 0},
	{Timer: 0},
	{Score: 0},
	{X: 0},
	{Y: 0},
	{On: 0},
	{IsTouched: 0},
	{Tile: 0},
	{kadr: 0},
	{Запуск: 0},
	{баннер: 0}
];

self.InstanceType = {
	Block: class extends self.ISpriteInstance {},
	Col1: class extends self.ISpriteInstance {},
	Col2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	SwapArray: class extends self.IArrayInstance {},
	MainArray: class extends self.IArrayInstance {},
	Function: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	LocalStorage: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Particles6: class extends self.IParticlesInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	bg_sprite: class extends self.ISpriteInstance {},
	menuplaybtn: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Textscores: class extends self.ITextInstance {},
	Textyours: class extends self.ITextInstance {},
	yourscoretxt: class extends self.ITextInstance {},
	yourhiscoretxt: class extends self.ITextInstance {},
	Textyourshiscore2: class extends self.ITextInstance {},
	btn_quit: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	barra_score: class extends self.ISpriteInstance {},
	distancesguisheet: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	image3: class extends self.ISpriteInstance {},
	image4: class extends self.ISpriteInstance {},
	image5: class extends self.ISpriteInstance {},
	Магия3ВРяд: class extends self.ISpriteInstance {},
	hiclipartcom: class extends self.ISpriteInstance {},
	share: class extends self.ISpriteInstance {},
	Block3: class extends self.ISpriteInstance {},
	Block4: class extends self.ISpriteInstance {},
	PADAET: class extends self.ISpriteInstance {},
	PADAET2: class extends self.ISpriteInstance {},
	PADAET3: class extends self.ISpriteInstance {},
	SADF: class extends self.ISpriteInstance {},
	БезИменил: class extends self.ISpriteInstance {},
	barra_score1: class extends self.ISpriteInstance {},
	image: class extends self.ISpriteInstance {},
	image6: class extends self.ISpriteInstance {},
	старт: class extends self.IButtonInstance {},
	бан: class extends self.IButtonInstance {},
	вид: class extends self.IButtonInstance {},
	GamePush: class extends self.IInstance {}
}