const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Browser.Acts.Close,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Touch: 0},
	{Button_Exit: 0},
	{Синусоида: 0},
	{PlayCVET: 0},
	{PlayDOL: 0},
	{about: 0},
	{Terms: 0},
	{close: 0},
	{chad_3b71654f3ad6485bb17a78023ebde3ae: 0},
	{Спрайт: 0},
	{fON: 0},
	{sdf: 0},
	{image: 0},
	{Спрайт3: 0},
	{image2: 0},
	{image3: 0},
	{image4: 0},
	{PrivacyCvetnoiBoom: 0},
	{PrivacyDolina: 0},
	{TextspitefontABOUT: 0},
	{Спрайт2: 0},
	{TextspitefontеtERMS: 0},
	{level: 0},
	{btn_lvl: 0},
	{Tween: 0},
	{Buttons: 0},
	{кЛИК: 0},
	{кЛИК2: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Button_Exit: class extends self.ISpriteInstance {},
	PlayCVET: class extends self.ISpriteInstance {},
	PlayDOL: class extends self.ISpriteInstance {},
	about: class extends self.ISpriteInstance {},
	Terms: class extends self.ISpriteInstance {},
	close: class extends self.ISpriteInstance {},
	chad_3b71654f3ad6485bb17a78023ebde3ae: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	fON: class extends self.ISpriteInstance {},
	sdf: class extends self.ISpriteInstance {},
	image: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	image2: class extends self.ISpriteInstance {},
	image3: class extends self.ISpriteInstance {},
	image4: class extends self.ISpriteInstance {},
	PrivacyCvetnoiBoom: class extends self.ITextInstance {},
	PrivacyDolina: class extends self.ITextInstance {},
	TextspitefontABOUT: class extends self.ISpriteFontInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	TextspitefontеtERMS: class extends self.ISpriteFontInstance {},
	btn_lvl: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}