const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.Button,
		C3.Plugins.Function,
		C3.Plugins.TextBox,
		C3.Behaviors.Flash,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.ScriptsInEvents.Gamesheet_Event2_Act1,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.ScriptsInEvents.Gamesheet_Event3_Act2,
		C3.ScriptsInEvents.Gamesheet_Event4_Act2
	];
};
self.C3_JsPropNameTable = [
	{xx: 0},
	{yy: 0},
	{Moved: 0},
	{Del: 0},
	{Block: 0},
	{BoardBg: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Browser: 0},
	{BtnReset: 0},
	{GameOver: 0},
	{txtScore: 0},
	{LocalStorage: 0},
	{fon: 0},
	{image2: 0},
	{image: 0},
	{txtScore2: 0},
	{image6: 0},
	{pngegg: 0},
	{pngegg2: 0},
	{pngwingcom: 0},
	{rew: 0},
	{full: 0},
	{Function: 0},
	{Login: 0},
	{Мигание: 0},
	{ок: 0},
	{Tween: 0},
	{FBlock: 0}
];

self.InstanceType = {
	Block: class extends self.ISpriteInstance {},
	BoardBg: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	txtScore: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	fon: class extends self.ISpriteInstance {},
	image2: class extends self.ISpriteInstance {},
	image: class extends self.ISpriteInstance {},
	txtScore2: class extends self.ITextInstance {},
	image6: class extends self.ISpriteInstance {},
	pngegg: class extends self.ISpriteInstance {},
	pngegg2: class extends self.ISpriteInstance {},
	pngwingcom: class extends self.ISpriteInstance {},
	rew: class extends self.IButtonInstance {},
	full: class extends self.IButtonInstance {},
	Function: class extends self.IInstance {},
	Login: class extends self.ITextInputInstance {},
	ок: class extends self.ISpriteInstance {},
	FBlock: class extends self.ISpriteInstance {}
}